### ISSUE TITLE
Improve position of truncated shapes

### ISSUE THREAD

**Issue by TTFH** [metarmask/teardown#11]
Move the truncated shapes an offset according to how much the shape were truncated on each axis to match the surrounding objects, for example:
![before](https://i.ibb.co/ZcL7sDb/teardown-2021-05-02-18-53-49-353.png)
![after](https://i.ibb.co/NTpBqVd/teardown-2021-05-02-18-54-23-298.png)

OR

Divide large shapes into many smaller Magica Voxel shapes and set the position of each one.
This may not work if a shape is in the shape of an L, and it's divided like: | _ and the size on a different axis that the longest one changes, but this should not be a problem since most large shapes are right parallelogrammic prisms.

OR

Find patterns on the shape and use a voxbox.

**Comment by metarmask** [comment]
For now, I have prioritized that each voxel that _is_ added is added in the correct spot, so things like this aren't misaligned:
![image](https://user-images.githubusercontent.com/7348146/116874161-216ec700-ac19-11eb-8ad0-5ae8c0e3dfc0.png)

**Comment by metarmask** [comment]
Dividing is attractive because it could represent all shapes. You could even put them in a compound so the resulting save is the same.

Finding patterns on the other hand would be more storage-efficient and easier to work with if you wanted to change it, but would be more complex, and still couldn't represent all shapes. Patterns should probably also be added for shapes of all sizes.

A fourth, crazy option would be to use a compound + one voxbox for each individual stretch of the same material. This would also fix shapes which use more of a material type than can fit in the standard palette. It would be a pain to change though, take up lots of space and probably slow loading the level.
